### ISSUE TITLE
Celery does not respect task expiry param

### ISSUE THREAD

**Issue by vmax-reef** [reef-technologies/cookiecutter-rt-django#3]
https://github.com/reef-technologies/cookiecutter-rt-django/blob/ea400831131687f83dfbd966daba42d307d93b00/%7B%7Bcookiecutter.repostory_name%7D%7D/app/src/%7B%7Bcookiecutter.django_project_name%7D%7D/settings.py#L124

To verify:
```
from <>.celery import app
app.conf.result_expires
# expected to return 604800 (int)
# but returns datetime.timedelta(1)
# datetime.timedelta(1).total_seconds() == 86400 (24h, which is the default) 
```

Suggested fix: 

Instead specify `CELERY_RESULT_EXPIRES` which saves the correct value

**Comment by mzukowski-reef** [comment]
Fixed
