### ISSUE TITLE
Block other domains on an Nginx level and do not use star for ALLOWED_HOSTS in production

### ISSUE THREAD

**Issue by mlech-reef** [reef-technologies/cookiecutter-rt-django#40]
The first is to block access via IP or other domains. It can be done by creating a default "blocking" server, e.g.:
```
server {
    listen 80 default_server;
    server_name _;
    return 444;
}
```
and one similar for HTTPS. It will solve "Invalid HTTP_HOST header" issues in Sentry.

The second is to catch unneeded traffic when the first one can not be used.

**Comment by ppolewicz** [comment]
Done
